#!/bin/sh
gsettings set org.gnome.desktop.background picture-uri "file://$1"
gsettings set org.gnome.desktop.screensaver picture-uri "file://$1"
if [ "`gsettings get org.gnome.desktop.background picture-options`" == "'none'" ]; then
    gsettings set org.gnome.desktop.background picture-options 'zoom'
    gsettings set org.gnome.desktop.screensaver picture-options 'zoom'
fi
